### PR TITLE
bump version to 0.18.3

### PR DESCRIPTION
**Pull request by silky**
not too much to change; but at least now it works with a more recent servant.

### CODE REVIEW

**Comment by soenkehahn** [comment]
LGTM.

I noticed that we don't have a working CI in this repo currently. (CI was using travis, but that is now defunct.) So I opened #13 to switch CI to github actions. I would like to merge #13 before this PR. If you have time I'd appreciate your review for #13. Sorry for the inconvenience.

**Comment by silky** [comment]
No worries; nice idea @soenkehahn; once that's merged I'll rebase this one :)

**Comment by soenkehahn** [comment]
@silky: Thanks for the review! #13 is merged now. Yeah, rebasing would trigger our shiny new CI, I hope. :)

**Comment by silky** [comment]
@soenkehahn - Just requires your approval to run the workflow now, I think.

**Comment by soenkehahn** [comment]
Ran successfully. Great, I'll merge. Many thanks for the PR!

**Pull request merged**
